### ISSUE TITLE
Certain Microsoft Excel copy/paste functionalities stop working

### ISSUE THREAD

**Issue by altquant** [hi5/CL3#13]
Hi, CL3 is great but I am having a few conflicts when using it in conjunction with Excel.
I am working on a Windows 10 machine with Excel 2016.

1. Copying formulas no longer works. If I copy a cell that has a formula and paste into another cell, it pastes only the value. Note that it *does* paste the formatting, just not the formula.

2. if I try to copy an entire row or column, I get an error message "the picture is too large and will be truncated". I still end up being able to copy the row, but the error message is unexpected.

3. if I copy a single cell and paste it into multiple cells, the default Excel behavior is that it pastes all the cells with the cell I copied. With CL3 on I instead get a message that "the data you're pasting isn't the same size as your selection. Do you want to paste anyway?". If I select OK only the single cell is pasted.

Can anyone corroborate these issues and if so, are there any workarounds / plans to make CL3 more compatible with Excel? Otherwise I will have to resort to disabling CL3 every time I work with Excel. Thanks a lot.

**Comment by hi5** [comment]
That is a known issue and due to the [AutoReplace feature/plugin](https://github.com/hi5/CL3#autoreplace-v14) - if you check the tray menu there is probably a checkmark :heavy_check_mark:  before AutoReplace to indicate it if is active. If so, uncheck it and pasting in Excel should no longer be an issue.

If you do use AutoReplace you can add `excel.exe` to the "Bypass" setting: bring up the CL3 menu, Special, AutoReplace - that should bring up the AutoReplace GUI where you can define the find/replace actions. There you can add a comma separated list of programs to exclude.

That said, if you don't have any Find/Replace actions in there adding excel.exe and saving it won't do much good as it won't save it in that case - this is a **bug**. I'm working on an update - mostly focusing on the ClipChain to allow the user to set the hotkey to "paste next item" in the chain (currently also ^v) - I'll update AutoReplace to:

a. by default include excel.exe
b. save correctly even if there aren't any Find/Replace actions
c. deactivate AutoReplace by default (currently it is Active by default)

Probably in the next few days.

For reference - Excel + AutoReplace is mentioned although briefly https://github.com/hi5/CL3/blob/master/changelog.md#v143

**Comment by hi5** [comment]
The above is now available in v1.95

**Comment by hi5** [comment]
Another Excel fix in v1.98 https://github.com/hi5/CL3
