### ISSUE TITLE
Clipboard entry always replaces File name in "Open/Save as" dialogs instead of adding to it

### ISSUE THREAD

**Issue by Spider-Can** [hi5/CL3#14]
Hi!
Let's say I want to save a file and add a value from the clipboard at the end of a suggested or existing filename. Once I place the cursor at the end and try to put a value from the clipboard history there it immediately replaces the entire name instead of appending it.

Does a workaround exist somewhere in the settings which I couldn't find or would this be an issue to investigate?

Thanks in advance for your help and feedback!

**Comment by hi5** [comment]
Never actually notice that - if it isn't too far down in the history you can try to cycle back to it using 
<kbd>#</kbd>+<kbd>v</kbd> - keep the Windows key pressed, tap v to cycle back, release the Windows key to paste the entry in the tooltip that should appear.

It is probably because of the menu that when it the File Save dialog gets focus again it automatically selects the entire (current or suggested) filename and before CL3 pastes. Also when I switch windows / programs and return to still open Save as dialog the entire (suggested) filename is selected again.

There is something you can try (comment below)

**Comment by hi5** [comment]
Create a new file in the `plugins\` folder. It must have the following name `PastePRIVATERULES.ahk`


```autohotkey
IfWinActive, Save As ; you may need to change this (1)
	ControlSend, Edit1, {end}, Save As
```

Save that file and restart CL3, that new file should check just before it paste if a "save as" window is active, if it is then send an <kbd>End</kbd> key stroke first before pasting, that should do it. It works here.

(1) Keep in mind the title may differ for various applications so you need to the check the window title. It might be case sensitive - if there are variations of the title (could be different languages for example) you can try to create a Group or use an #If WinActive or a RegEx window title:

https://www.autohotkey.com/docs/commands/GroupAdd.htm
https://www.autohotkey.com/docs/commands/_If.htm
https://www.autohotkey.com/docs/commands/SetTitleMatchMode.htm
