### ISSUE TITLE
I don't understand the point of "more history"? 

### ISSUE THREAD

**Issue by Skrell** [hi5/CL3#21]
Can you please explain?

**Comment by hi5** [comment]
By default the menu shows the `a` to `r` options as history items (18 items). 
The reason is that I want `s` to always be for `Special` (plugins) and `t` for `Templates`
So the main menu will always have a maximum of 18 clipboard history entries.

But 18 is also very limited, so the 19th 20th etc are in `z. More history` - in the settings you can control how many items the More history submenu should show, by default 26 (`a-z`) for relatively quick access. 

If you don't want to see it at all you can turn it off using "Setup menu" and uncheck it.

**Settings**

![settings](https://user-images.githubusercontent.com/1973899/212971479-b44ee835-7b60-436a-86bd-2d6fc581ba21.png)
